# This is a basic workflow to help you get started with Actions

name: Deploy develop

on:
  workflow_run:
    workflows: [Build CI]
    types: [completed]
    branches: [develop, master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: behe/heroku-build@v1.1
        with:
          app-name: "clean-node-advanced-develop"
          api-key: "${{secrets.HEROKU_API_KEY}}"
